Repository tryber/sd-07-project-recipes-app, pull requests merged in 2021-02, with the labels that each got.

#553 Adicionando elementos CSS
  src/App.css
  src/components/Footer.css
  src/components/Footer.jsx
  src/components/Header.css
  src/components/Header.jsx
  src/images/fire_base.gif
  src/pages/Profile.jsx
Labels: code-review

#543 [GROUP 12] - Tela de detalhes de uma receita
  package-lock.json
  package.json
  src/App.js
  src/components/Loading.jsx
  src/components/RecipeDetailsButton.jsx
  src/components/RecipeDetailsHeader.jsx
  src/components/RecipeDetailsIngredients.jsx
  src/components/RecipeDetailsModal.jsx
  src/components/RecipeVideo.jsx
  src/components/RecommendedRecipes.jsx
  src/components/index.js
  src/context/RecipeContext.js
  src/images/blackHeartIcon.svg
  src/pages/ExploreArea.jsx
  src/pages/ExploreIngredients.jsx
  src/pages/RecipeDetails.css
  src/pages/RecipeDetails.jsx
Labels: code-review

#550 Main group 28 tela principal receitas
  src/App.js
  src/components/CardsDrink.jsx
  src/components/CardsFood.jsx
  src/pages/Bebidas.jsx
  src/pages/Comidas.jsx
  src/pages/NotFound.jsx
Labels: code-review

#489 main-group-25-req-25-ao-32
  src/common/CategoryPanel/components/CategoryButton.js
  src/common/CategoryPanel/index.js
  src/common/NavigationButton/index.js
  src/common/SearchBar/index.js
  src/context/AppContext.js
  src/scenes/Bebidas/index.js
  src/scenes/Comidas/index.js
  src/services/API.js
Labels: code-review

#604 [GROUP 12] - Tela de receitas em progresso
  src/App.js
  src/components/IngredientsCheckbox.jsx
  src/components/IngredientsInProgress.jsx
  src/components/RecipeDetailsButton.jsx
  src/components/RecipeDetailsHeader.jsx
  src/components/RecipeDetailsIngredients.jsx
  src/components/RecommendedRecipesBody.jsx
  src/components/index.js
  src/context/RecipeContext.js
  src/pages/DoneRecipes.jsx
  src/pages/RecipeDetails.css
  src/pages/RecipeDetails.jsx
  src/services/index.js
Labels: code-review

#607 [Group 23] - Receitas Favoritas
  src/components/FoodThumb/index.js
  src/pages/Comidas/index.js
  src/pages/ReceitasFavoritas/index.js
  src/pages/ReceitasFavoritas/styles.css
  src/routes/index.js
  src/services/localstorage.js
Labels: code-review

#625 Main group 21 profile
  src/App.js
  src/components/Header.js
  src/components/HeaderNoSearch.js
  src/pages/Perfil.js
  src/pages/Profile.js
Labels: code-review

#576 Main group 28 tela de receitas botoes categoria
  src/components/ButtonCategoriesDrink.jsx
  src/components/ButtonCategoriesFood.jsx
  src/components/CardsDrink.jsx
  src/context/Provider.jsx
  src/pages/Bebidas.jsx
  src/pages/Comidas.jsx
Labels: code-review

#727 Commitando requisitos 83 e 87.
  src/pages/Profile.js
  src/services/localStorageFunctions.js
Labels: code-review

#774 Requisitos 54, 55, 56, 57, 58 e 59 concluiídos
  src/App.css
  src/components/Header.jsx
  src/components/RecipesDoneCard.jsx
  src/context/Provider.jsx
  src/pages/RecipesDone.jsx
  src/services/localStorage.js
Labels: code-review

#755 Main group 28 tela de detalhes de receita
  package-lock.json
  package.json
  src/components/FavoriteHeart.jsx
  src/context/Provider.jsx
  src/pages/DetalhesBebidas.jsx
  src/pages/DetalhesReceita.jsx
Labels: code-review

#675 [Main Group 19] Receita em Progresso
  src/css/details.css
  src/localStorage/inProgressRecipes.js
  src/pages/DrinkInProgress.js
  src/pages/FoodInProgress.js
Labels: Tela de receita em progresso, code-review

#775 Conciliação main atual com os requisitos 47 a 53
  src/components/Header/style.css
  src/components/IngredientsTable/index.js
  src/pages/Progress/Actions.js
  src/pages/Progress/index.js
  src/pages/Progress/style.css
  src/services/api.js
Labels: code-review

#875 [Main Group 19] Receitas Feitas
  src/pages/DoneRecipe.js
Labels: Tela de receitas feitas, code-review

#905 Implementação dos botãos de explorar
  src/pages/ExplorarBebidas.jsx
  src/pages/ExplorarComidas.jsx
Labels: code-review

#900 Main group 7 requisito tela de receitas favoritas
  src/App.css
  src/components/RecipesDoneCard.jsx
  src/components/RecipesFavoriteCard.jsx
  src/services/localStorage.js
Labels: code-review

#902 Main group 28 tela de receitas feitas
  package-lock.json
  src/components/FavoriteHeart.jsx
  src/context/Provider.jsx
  src/pages/DetalhesBebidas.jsx
  src/pages/DetalhesReceita.jsx
  src/pages/ProcessoBebida.jsx
  src/pages/ProcessoReceita.jsx
  src/pages/ReceitasFeitas.jsx
Labels: code-review

#919 Requisitos 60, 61, 62, 63, 63, 65 e 66 Apenas CSS-3
  src/App.css
  src/components/RecipesDoneCard.jsx
  src/components/RecipesFavoriteCard.jsx
Labels: code-review

#914 Main group 28 tela de explorar ingredientes
  src/pages/BebidasPorIngredientes.jsx
  src/pages/ComidasPorIngredientes.jsx
Labels: code-review

#927 Main group 28 tela de explorar por origem
  package-lock.json
  package.json
  src/components/ButtonCategoriesDrink.jsx
  src/components/CardsDrink.jsx
  src/components/CardsFood.jsx
  src/components/Login.jsx
  src/index.css
  src/pages/ComidasPorOrigem.jsx
  src/pages/DetalhesBebidas.jsx
  src/pages/DetalhesReceita.jsx
  src/pages/ProcessoBebida.jsx
  src/pages/ProcessoReceita.jsx
  src/pages/ReceitasFeitas.jsx
  src/styles/components/cardsDrink.css
  src/styles/components/cardsFood.css
  src/styles/components/footer.css
  src/styles/components/login.css
  src/styles/pages/detalhesBebidas.css
  src/styles/pages/detalhesReceita.css
  src/styles/pages/processoBebida.css
  src/styles/pages/processoReceita.css
  src/styles/pages/receitasFeitas.css
Labels: code-review

#961 Main group 22 favorite page
  src/components/ButtonsFavoritePage.js
  src/pages/CocktailDetails.js
  src/pages/FavoriteRecipes.js
  src/pages/MealDetails.js
Labels: code-review

#969 [GROUP 12] - Estilização do logo
  src/images/packageDelivery.svg
  src/pages/Login.css
  src/pages/Login.jsx
Labels: code-review

#975 [GROUP 12] Ajustado logo
  src/pages/Login.css
Labels: code-review

#970 [Main group 19] fix header
  src/functions/index.js
  src/pages/DoneRecipe.js
  src/pages/DrinkIngredients.js
  src/pages/FavoriteRecipe.js
  src/pages/FoodIngredients.js
  src/pages/Profile.js
Labels: code-review

#983 [Main Group 19] Estilizacao dos botões na tela de Explorar
  src/pages/DrinkExplore.js
  src/pages/Explore.js
  src/pages/FoodExplore.js
Labels: Tela de explorar, code-review
